### ISSUE TITLE
Environment Variable Not Found Error in Deputy Component

### ISSUE THREAD

**Issue by faizanars** [Open-Cyber-Range/Deputy#1]
**Description:**
Hello,

My name is Muhammad Faizan Arshad, a student at Air University, currently pursuing a Bachelor's in Cybersecurity. I am working on the deployment of the "deputy" component of the CR14 Open Cyber Range and have encountered an error related to environment variables.

**Error Message:**
![image](https://github.com/Open-Cyber-Range/Deputy/assets/123324150/9582356e-a321-4b8b-aac3-837ba1bef0f5)
This error is persistent over the changing of paths, and occurs even when the package file is in the current working (present) directory.

**Steps to Reproduce:**

1. Set up the project as per the documentation.
2. Attempt to run the deputy publish command.

**Environment:**

Operating System: Ubuntu LTS
Node.js version: Latest Version
Keycloak version: Latest Version

**.env File Configuration:**

```NEXT_PUBLIC_KEYCLOAK_REALM=myrealm
NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8080/auth
NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=deputy
KEYCLOAK_CLIENT_ID=deputy
KEYCLOAK_CLIENT_SECRET= [same as issued by keycloak]
KEYCLOAK_ISSUER=http://localhost:8080/realms/myrealm
```
**Environment Variables Passed:**

```
DEPUTY_CONFIG_FOLDER="/home/ocr/Desktop/Deputy/devcontainer/deputy-development/"

DEPUTY_CONFIG="/home/ocr/Desktop/Deputy/devcontainer/deputy-development/deputy-configuration.toml"
```
**Troubleshooting Steps Taken:**

1. Verified .env file content.
2. Exported environment variables manually.
3. Ensured Keycloak server is running and accessible.

Despite these efforts, the issue persists. I would greatly appreciate any guidance or assistance in resolving this error.

Thank you for your support.

Best regards,
Muhammad Faizan Arshad

**Comment by raltm2e** [comment]
It seems like You are calling `deputy` from outside the devcontainer.

1) Have you tried running
 `:~$ deputy`
 in the `deputy-development` Docker container?

2) Another option, if you have Rust on your system, is to run
 `:~$ cargo run -p deputy` 

 Please let us know if this resolves your issue

EDIT:
In addition, please verify what are the file rights of `deputy-configuration.toml` and that `deputy` has rights to read that file. 
A quick fix would be giving 777 rights to the file.

**Comment by faizanars** [comment]
Hello! 
 
Thank you for responding to me. I've tried both the solutions that you've provided but unfortunately, they don't work. I've tried updating the docker container and then ran it using ```cargo```. Moreover, changed permissions of the ```deputy-configuration.toml``` file but still, no progress.

Kindly help me resolve this!
Thank you,
Best Regards.

Edit: Upon pulling the docker container of deputy-development, this is the error that is received:
``` => [deputy-development internal] load build definition from Dockerfile                                                                                            1.0s
 => => transferring dockerfile: 1.32kB                                                                                                                             0.0s
 => [deputy-development internal] load .dockerignore                                                                                                               0.8s
 => => transferring context: 2B                                                                                                                                    0.0s
 => ERROR [deputy-development internal] load metadata for nexus.ocr.cr14.net:8003/rust-development:latest                                                          0.8s
------
 > [deputy-development internal] load metadata for nexus.ocr.cr14.net:8003/rust-development:latest:
------
failed to solve: nexus.ocr.cr14.net:8003/rust-development:latest: failed to do request: Head "https://nexus.ocr.cr14.net:8003/v2/rust-development/manifests/latest": dial tcp: lookup nexus.ocr.cr14.net on 127.0.0.53:53: no such host
```

**Comment by raltm2e** [comment]
There seems to be a mismatch of the file name itself. In `deputy/src/constants.rs` a file "configuration.toml" is required. 

Please rename `deputy-configuration.toml` --> `configuration.toml` as a temporary fix.

The underlying problem will be resolved in the future.

**Comment by faizanars** [comment]
Thank you for responding! Following were the changes made:

- Changed the file name from ```deputy-configuration.toml``` to ```configuration.toml```, along with every occurrence in ```deputy```, ```deputy-release``` and environment variables in ```~/.bashrc```. 

After this, I tried running ```deputy``` and it worked just fine! However, when I try to publish a package, it gives the following error (Please note that the ```package.toml``` is available in the present working directory).

Issue: 
![image](https://github.com/Open-Cyber-Range/Deputy/assets/123324150/679f0bf7-2272-4f79-8a62-fc0fe5c27f52)

Now, I totally understand that a ```Readme``` file is required, but the error persists even after ```Readme``` file is made. Are there any fixes to this, and kindly give me the context of this ```Readme``` file and what the ```package.toml``` should contain. Moreover, kindly explain the deputy CLI commands in a little detail as I couldn't get a full idea from the documentation provided at ```documentation.opencyberrange.ee/docs```. 

Thank you, I'll be really grateful.

Best Regards,
Muhammad Faizan Arshad

**Comment by raltm2e** [comment]
Try running the `deputy publish` from the package's root directory, meaning the same directory where the `package.toml` exists.

An example of a `package.toml` can be found in the [tests here](https://github.com/Open-Cyber-Range/Deputy/blob/2ed1a70ec30185c477dae9965eef9a5b664960f8/deputy-library/src/test.rs#L26).

The CLI commands can be listed by just running `deputy` in the CLI. It's also possible to get a more detailed description of each command, for example `deputy fetch --help`.
